name: cfn_model

on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Allows both ruby versions to run before failing
      matrix:
        ruby: ['2.5', '3.0']

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    #- name: Rubocop lint
    #  run: bundle exec rubocop -D
    - name: Rspec tests
      run: bundle exec rspec --require spec_helper spec

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: commit
    steps:
      # is this the same commit hash we saw in commit?
      - uses: actions/checkout@v2
      - run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --prune --unshallow
      - name: Publish to RubyGems
        id: publish
        run: bash ./publish.sh
        env:
          rubygems_api_key: ${{secrets.rubygems_api_key}}
      - name: Create release with changelog
        id: gh_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          version: ${{ steps.publish.outputs.cfn_model_version }}
